### ISSUE TITLE
Unable to update group

### ISSUE THREAD

**Issue by carloscorrales** [fiwoo-platform/user-management#117]
When trying to update a group, I receive a 422 error. For instance, try to execute the following CURL (modify the authorization header

`curl "https://platform.fiwoo.eu/api/user-management/assets/9" -X PUT -H "Cookie: G_ENABLED_IDPS=google; connect.sid=s^%^3AusHQ8uFdoNO5l0UTsvvvUiP8yCZIPxE5.y2yBjIqwyl1UOglZ1g9SBYyAqmqAo6geFW298k6wtn0; JSESSIONID=85E23AC7525E5D2637E88728017DB8FC" -H "Origin: https://platform.fiwoo.eu" -H "Accept-Encoding: gzip, deflate, br" -H "Accept-Language: es,en-US;q=0.9,en;q=0.8" -H "Authorization: Bearer 72deb08f-bb68-4928-ba16-78ebb994c762" -H "Content-Type: application/json" -H "Accept: application/json" -H "Referer: https://platform.fiwoo.eu/" -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 Mobile/14E304 Safari/602.1" -H "Connection: keep-alive" --data-binary "^{^\^"name^\^":^\^"Test Users Parent Group^\^",^\^"description^\^":^\^"This Group is the parent of the other test users groups^\^",^\^"type^\^":^\^"TestGroup^\^",^\^"parents^\^":^[^],^\^"childrens^\^":^[^{^\^"id^\^":7,^\^"name^\^":^\^"Test Users Group A^\^",^\^"description^\^":^\^"This is a group for some of the test users^\^",^\^"type^\^":^\^"TestGroup^\^",^\^"parents^\^":^[^],^\^"children^\^":^[^],^\^"itemName^\^":^\^"Test Users Group A^\^"^},^{^\^"id^\^":8,^\^"name^\^":^\^"Test Users Grupo B^\^",^\^"description^\^":^\^"This is a group for other test users^\^",^\^"type^\^":^\^"TestGroup^\^",^\^"parents^\^":^[^],^\^"children^\^":^[^],^\^"itemName^\^":^\^"Test Users Grupo B^\^"^}^]^}" --compressed`

**Comment by rcarballoc** [comment]
No errors detected, please, could u check again?
